
    create table contato (
       id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255),
        nome varchar(255),
        sobre_nome varchar(255),
        primary key (id)
    );

    create table contato_enderecos (
       contato_id bigint not null,
        enderecos_cep varchar(255) not null
    );

    create table endereco (
       cep varchar(255) not null,
        bairro varchar(255),
        cidade varchar(255),
        logradouro varchar(255),
        tipo_de_endereco varchar(255),
        uf varchar(255),
        primary key (cep)
    );

    alter table contato 
       add constraint UK_v6ynadwmlgiar3tqrydve73q unique (cpf);

    alter table contato 
       add constraint UK_4ds5brlm0e7etaij4k5twocp4 unique (email);

    alter table contato_enderecos 
       add constraint FKsqt6yq8dpk76s7sf949f0e3ml 
       foreign key (enderecos_cep) 
       references endereco;

    alter table contato_enderecos 
       add constraint FKskjnmn0cafqst8cf7yhjxt5qu 
       foreign key (contato_id) 
       references contato;
